plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

packageExtensions:
  # Fixes shopify build system build
  'webpack@*':
    dependencies:
      '@types/json-schema': "*"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
