
name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - '*'
jobs:
  build: # make sure build/ci work properly
    runs-on: tutorbookapp/github-action@master # use this fork until it is merged: https://github.com/cypress-io/circleci-orb/issues/312
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install
      - run: |
          yarn run test
      - run: |
          yarn run build
